version: "3.9"
services:
  app:
    build:
      context: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    container_name: apple-sso-app
    environment:
      - DEBUG=True
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate --noinput &&
            python manage.py runserver 0.0.0.0:8000"